### ISSUE TITLE
can download any file

### ISSUE THREAD

**Issue by twstagg** [PHSCDC/backup-webapp#1]
stupid php

**Comment by majiru** [comment]
This is not an issue with shell_exec this is an issue with the passing and parsing of the information to the header call in  the download.php file. This has nothing to do with the shell_exec call in the previous files.  This is done by usin the directory shortcut (..).  This is due to the fact that the directory is hard coded, and the download is prepared by simply pointing to the file and not actually preparing a download.  Example: By changing the name in the forum to ../etc/passwd you can easily download the associated file.

**Comment by twstagg** [comment]
you don't even need to use .. but yeah

**Comment by jummy0** [comment]
fixde
